### PR TITLE
flightgear-git: Depend on osgxr to enable VR

### LINKED ISSUE #1: [flightgear-git] VR dependencies
As noted here:
https://aur.archlinux.org/packages/flightgear-git#comment-846624

Flightgear next will now make use of osgXR if available to enable some basic VR support, otherwise it will try to build its own static built-in version of osgXR which would implicitly depend on OpenXR.

So 3 possible options (in order of preference):

1) add 'libosgXR' to depends so that the osgXR shared library provided by https://aur.archlinux.org/packages/osgxr/ (which pulls in 'openxr') is automatically used (cmake ENABLE_VR and SYSTEM_OSGXR will both default to ON)

2) add the cmake option -DSYSTEM_OSGXR=OFF and add 'openxr' 'libglvnd' to depends, so flightgear will attempt to build its own static built-in version of osgXR (which would depend on OpenXR (and GLX)).

3) add the cmake option -DENABLE_VR=OFF to prevent the implicit dependencies, but obviously disables any VR support.

My plan is to implement option (1) and get it tested in a clean chroot (once I can figure out getting the dependencies that way). osgXR's API isn't necessarily stable yet (and flightgear is the only real user I think). I already update osgXR's AUR PKGBUILD if needed before updating flightgear next branch.

If a new release of flightgear is made and further API changes are necessary I'll deal with it then, hopefully just requiring a rebuild against the latest osgXR. Worst case one of the packages can be switched to option (2).

### PR DESCRIPTION
**Pull request by amalon**
Depend on osgxr so that VR support gets enabled.

Fixes #1

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
For the PKGBUILD to be updated on the AUR, the pkgver or the pkgrel needs to be updated.

if you run `makepkg` it should update the pkgver, if the commit is the same, then the pkgrel should be updated.

**Comment by amalon** [comment]
> For the PKGBUILD to be updated on the AUR, the pkgver or the pkgrel needs to be updated.
> 
> if you run `makepkg` it should update the pkgver, if the commit is the same, then the pkgrel should be updated.

Okay, no problem, i've updated my branch (I wasn't sure before whether to include that change or not).

I couldn't figure out how to make flightgear-git depend on libosgXR (provided by osgxr package) and for aur helpers to work and find the dependency, so I'm guessing that doesn't work with AUR, hence why i depended directly on the osgxr package.

**Comment by acxz** [comment]
You can specify packages that are listed as `provides` in the PKGBUILD. So you can just type in `libosgXR` in the makedeps, instead of osgxr.

> guessing that doesn't work with AUR

It will be the same as it is with the official repos.

**Comment by amalon** [comment]
> You can specify packages that are listed as `provides` in the PKGBUILD. So you can just type in `libosgXR` in the makedeps, instead of osgxr.

Thats what I thought, but when I tried that, paru didn't seem able to find what provides libosgXR, even with Provides enabled in the config, unless it already had osgxr installed. Actually I added to depends not makedepends, but its needed at runtime too so I'm not sure makedepends would be right.

I'm pretty new to paru though, took a fair bit of fiddling to get this far :-)

**Comment by acxz** [comment]
> Actually I added to depends not makedepends, but its needed at runtime too so I'm not sure makedepends would be right.

Ah yes mb, depends.

> paru didn't seem able to find what provides libosgXR

yeah paru's dep resolver (esp in chroot mode) needs some work imo, but yay probably would've worked and maybe paru w/o chroot mode.

Is there another package that provides `libosgXR` in the AUR or the official repos? If so then you should change it back, if not, then using the provided package name instead of the actual name would be incorrect.

**Comment by amalon** [comment]
> > paru didn't seem able to find what provides libosgXR
> 
> yeah paru's dep resolver (esp in chroot mode) needs some work imo, but yay probably would've worked and maybe paru w/o chroot mode.

When I removed all trace of osgXR packages from my system, and tried adding libosgXR to depends in `~/.cache/yay/flightgear-git/PKGBUILD` and committed it so yay didn't overwrite, yay didn't pick up the dependency and couldn't build it:
```
$ yay -S flightgear-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  flightgear-git-2020.4.0r15376.4e432b3f8-1

  1 flightgear-git                           (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: PKGBUILD up to date, Skipping (1/0): flightgear-git
  1 flightgear-git                           (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
 -> flightgear-git: No changes -- skipping

==> Proceed with install? [Y/n] 
:: (1/1) Parsing SRCINFO: flightgear-git
==> Making package: flightgear-git 2020.4.0r15830.5d6ac7a1c-1 (Sun 11 Sep 2022 16:12:30 BST)
==> Retrieving sources...
  -> Updating flightgear git repo...
==> Validating source files with sha256sums...
    flightgear ... Skipped
==> Making package: flightgear-git 2020.4.0r15830.5d6ac7a1c-1 (Sun 11 Sep 2022 16:12:35 BST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> libosgXR
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
 -> error making: flightgear-git
```
but perhaps its wanting that dependency info straight from AUR beforehand (which doesn't have it yet).

> Is there another package that provides `libosgXR` in the AUR or the official repos?

no. I created the osgXR library and added to AUR in the form of the osgxr package only.

> If so then you should change it back, if not, then using the provided package name instead of the actual name would be incorrect.

So given there's just the one, and we can't easily be sure the aur helpers will work with it, shall we just stick to depending on osgxr unless the need arises to have more than one?

**Comment by acxz** [comment]
> So given there's just the one, and we can't easily be sure the aur helpers will work with it, shall we just stick to depending on osgxr unless the need arises to have more than one?

Yep!

**Review by acxz — APPROVED** [review]

**Comment by amalon** [comment]
thanks

**Pull request merged**
